# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from login import *
import sqlite3
import ibm_db
import ibmdbpy


class Ui_SignUp(object):
    conn = ""

    def cloudConnectiontwo():
        print("called")
        dsn_driver = "IBM DB2 ODBC DRIVER"
        dsn_databases = "BLUDB"
        dsn_hostname = 'dashdb-txn-sbox-yp-lon02-01.services.eu-gb.bluemix.net'
        dsn_port = "50000"
        dsn_protocal = "TCPIP"
        dsn_uid = 'wkg83160'
        dsn_pwd = "8g2kgt18+2tljbrb"
        dsn = ("DRIVER={{IBM DB2 ODBC DRIVER}};"
               "DATABASE={0};"
               "HOSTNAME = {1};"
               "PORT = {2};"
               "PROTOCOL = TCPIP;"
               "UID={3};"
               "pwd ={4};").format(dsn_databases, dsn_hostname, dsn_port, dsn_uid, dsn_pwd)
        global conn
        conn = ibm_db.connect(dsn, "", "")
        print("cloud connected")

    def insertData(self):
        Ui_SignUp.cloudConnectiontwo()
        username = self.unameInp.text()
        password = self.pswdInp.text()
        email = self.emailInp.text()
        conatct = int(self.contactInp.text())
        member1_name = self.mem1NameInp.text()
        mamber1_email = self.mem1EmailInp.text()
        member2_name = self.mem2NameInp.text()
        member2_email = self.mem2EmailInp.text()
        print(member1_name, mamber1_email, member2_name, member2_email)
        query = "insert into WKG83160.USERS1(username, pasd, email, contact, REFPERSON1, REFPERSON2, REFPERSON1EMAIL, REFPERSON2EMAIL) values ('%s','%s','%s','%s','%s','%s','%s','%s')" % (
        username, password, email, conatct, member1_name, member2_name, mamber1_email, member2_email)
        stmt = ibm_db.exec_immediate(conn, query)
        self.clickLogin()

    def clickLogin(self):
        self.window = QtWidgets.QMainWindow()
        self.uilogin = Ui_Login()
        self.uilogin.setupUiLogin(self.window)
        self.window.show()

    def setupUiSignUp(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(960, 640)
        MainWindow.setMinimumSize(QtCore.QSize(960, 640))
        MainWindow.setMaximumSize(QtCore.QSize(960, 640))
        MainWindow.setStyleSheet("background-image:url(:/newPrefix/watsonLogo.jpeg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.unameLbl = QtWidgets.QLabel(self.centralwidget)
        self.unameLbl.setGeometry(QtCore.QRect(60, 190, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.unameLbl.setFont(font)
        self.unameLbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.unameLbl.setScaledContents(False)
        self.unameLbl.setWordWrap(False)
        self.unameLbl.setOpenExternalLinks(False)
        self.unameLbl.setObjectName("unameLbl")
        self.signupLbl = QtWidgets.QLabel(self.centralwidget)
        self.signupLbl.setGeometry(QtCore.QRect(420, 0, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.signupLbl.setFont(font)
        self.signupLbl.setStyleSheet("color:rgb(255, 255, 255);")
        self.signupLbl.setObjectName("signupLbl")
        self.unameInp = QtWidgets.QLineEdit(self.centralwidget)
        self.unameInp.setGeometry(QtCore.QRect(220, 200, 231, 25))
        self.unameInp.setStyleSheet("color: rgb(255, 255, 255);")
        self.unameInp.setText("")
        self.unameInp.setObjectName("unameInp")
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(220, 520, 112, 34))
        #######################login button clicked############
        self.loginBtn.clicked.connect(self.clickLogin)
        #######################################################
        font = QtGui.QFont()
        font.setPointSize(15)
        self.loginBtn.setFont(font)
        self.loginBtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.loginBtn.setObjectName("loginBtn")
        self.submitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.submitBtn.setGeometry(QtCore.QRect(410, 520, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.submitBtn.setFont(font)
        self.submitBtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.submitBtn.setAutoDefault(True)
        self.submitBtn.setDefault(False)
        self.submitBtn.setFlat(False)
        self.submitBtn.setObjectName("submitBtn")
        ############################# insert data ##################
        self.submitBtn.clicked.connect(self.insertData)
        ############################################################
        self.pswdLbl = QtWidgets.QLabel(self.centralwidget)
        self.pswdLbl.setGeometry(QtCore.QRect(60, 240, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pswdLbl.setFont(font)
        self.pswdLbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.pswdLbl.setObjectName("pswdLbl")
        self.pswdInp = QtWidgets.QLineEdit(self.centralwidget)
        self.pswdInp.setGeometry(QtCore.QRect(220, 260, 231, 25))
        self.pswdInp.setStyleSheet("color: rgb(255, 255, 255);")
        self.pswdInp.setText("")
        self.pswdInp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pswdInp.setObjectName("pswdInp")
        self.emailLbl = QtWidgets.QLabel(self.centralwidget)
        self.emailLbl.setGeometry(QtCore.QRect(60, 310, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.emailLbl.setFont(font)
        self.emailLbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.emailLbl.setScaledContents(False)
        self.emailLbl.setWordWrap(False)
        self.emailLbl.setOpenExternalLinks(False)
        self.emailLbl.setObjectName("emailLbl")
        self.contactInp = QtWidgets.QLineEdit(self.centralwidget)
        self.contactInp.setGeometry(QtCore.QRect(220, 380, 231, 25))
        self.contactInp.setStyleSheet("color: rgb(255, 255, 255);")
        self.contactInp.setText("")
        self.contactInp.setObjectName("contactInp")
        self.emailInp = QtWidgets.QLineEdit(self.centralwidget)
        self.emailInp.setGeometry(QtCore.QRect(220, 320, 231, 25))
        self.emailInp.setStyleSheet("color: rgb(255, 255, 255);")
        self.emailInp.setObjectName("emailInp")
        self.contactLbl = QtWidgets.QLabel(self.centralwidget)
        self.contactLbl.setGeometry(QtCore.QRect(60, 360, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.contactLbl.setFont(font)
        self.contactLbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.contactLbl.setObjectName("contactLbl")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(590, 520, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.resetBtn.setFont(font)
        self.resetBtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.resetBtn.setAutoDefault(True)
        self.resetBtn.setDefault(False)
        self.resetBtn.setFlat(False)
        self.resetBtn.setObjectName("resetBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 60, 121, 111))
        self.label.setStyleSheet("background-image:url(:/newPrefix/User-Login-128.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)

        ##################form of members #######################
        self.member1Lbl = QtWidgets.QLabel(self.centralwidget)
        self.member1Lbl.setGeometry(QtCore.QRect(670, 90, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.member1Lbl.setFont(font)
        self.member1Lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.member1Lbl.setObjectName("member1Lbl")
        self.mem1NameLbl = QtWidgets.QLabel(self.centralwidget)
        self.mem1NameLbl.setGeometry(QtCore.QRect(510, 160, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mem1NameLbl.setFont(font)
        self.mem1NameLbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem1NameLbl.setObjectName("mem1NameLbl")
        self.mem1NameInp = QtWidgets.QLineEdit(self.centralwidget)
        self.mem1NameInp.setGeometry(QtCore.QRect(670, 180, 231, 25))
        self.mem1NameInp.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem1NameInp.setText("")
        self.mem1NameInp.setObjectName("mem1NameInp")
        self.mem1EmailLbl = QtWidgets.QLabel(self.centralwidget)
        self.mem1EmailLbl.setGeometry(QtCore.QRect(510, 220, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mem1EmailLbl.setFont(font)
        self.mem1EmailLbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem1EmailLbl.setObjectName("mem1EmailLbl")
        self.mem1EmailInp = QtWidgets.QLineEdit(self.centralwidget)
        self.mem1EmailInp.setGeometry(QtCore.QRect(670, 240, 231, 25))
        self.mem1EmailInp.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem1EmailInp.setText("")
        self.mem1EmailInp.setObjectName("mem1EmailInp")
        self.mem2EmailInp = QtWidgets.QLineEdit(self.centralwidget)
        self.mem2EmailInp.setGeometry(QtCore.QRect(670, 430, 231, 25))
        self.mem2EmailInp.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem2EmailInp.setText("")
        self.mem2EmailInp.setObjectName("mem2EmailInp")
        self.mem2NameInp = QtWidgets.QLineEdit(self.centralwidget)
        self.mem2NameInp.setGeometry(QtCore.QRect(670, 370, 231, 25))
        self.mem2NameInp.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem2NameInp.setText("")
        self.mem2NameInp.setObjectName("mem2NameInp")
        self.mem2EmailLbl = QtWidgets.QLabel(self.centralwidget)
        self.mem2EmailLbl.setGeometry(QtCore.QRect(510, 410, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mem2EmailLbl.setFont(font)
        self.mem2EmailLbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem2EmailLbl.setObjectName("mem2EmailLbl")
        self.mem2NameLbl = QtWidgets.QLabel(self.centralwidget)
        self.mem2NameLbl.setGeometry(QtCore.QRect(510, 350, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mem2NameLbl.setFont(font)
        self.mem2NameLbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem2NameLbl.setObjectName("mem2NameLbl")
        self.member2Lbl = QtWidgets.QLabel(self.centralwidget)
        self.member2Lbl.setGeometry(QtCore.QRect(670, 280, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.member2Lbl.setFont(font)
        self.member2Lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.member2Lbl.setObjectName("member2Lbl")
        self.member1Lbl_3 = QtWidgets.QLabel(self.centralwidget)
        self.member1Lbl_3.setGeometry(QtCore.QRect(240, 110, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.member1Lbl_3.setFont(font)
        self.member1Lbl_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.member1Lbl_3.setObjectName("member1Lbl_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Signup"))
        self.unameLbl.setText(_translate("MainWindow", "USERNAME"))
        self.signupLbl.setText(_translate("MainWindow", "SIGNUP"))
        self.unameInp.setPlaceholderText(_translate("MainWindow", "username"))
        self.loginBtn.setText(_translate("MainWindow", "LOGIN"))
        self.submitBtn.setText(_translate("MainWindow", "SUBMIT"))
        self.pswdLbl.setText(_translate("MainWindow", "PASSWORD"))
        self.pswdInp.setPlaceholderText(_translate("MainWindow", "password"))
        self.emailLbl.setText(_translate("MainWindow", "EMAIL ID"))
        self.contactInp.setPlaceholderText(_translate("MainWindow", "contact"))
        self.emailInp.setPlaceholderText(_translate("MainWindow", "email"))
        self.contactLbl.setText(_translate("MainWindow", "CONTACT"))
        self.resetBtn.setText(_translate("MainWindow", "RESET"))
        self.member1Lbl.setText(_translate("MainWindow", "MEMBER 1"))
        self.mem1NameLbl.setText(_translate("MainWindow", "NAME"))
        self.mem1NameInp.setPlaceholderText(_translate("MainWindow", "member 1 name"))
        self.mem1EmailLbl.setText(_translate("MainWindow", "EMAIL ID"))
        self.mem1EmailInp.setPlaceholderText(_translate("MainWindow", "member 1 email"))
        self.mem2EmailInp.setPlaceholderText(_translate("MainWindow", "member 2 email"))
        self.mem2NameInp.setPlaceholderText(_translate("MainWindow", "member 2 name"))
        self.mem2EmailLbl.setText(_translate("MainWindow", "EMAIL ID"))
        self.mem2NameLbl.setText(_translate("MainWindow", "NAME"))
        self.member2Lbl.setText(_translate("MainWindow", "MEMBER 2"))
        self.member1Lbl_3.setText(_translate("MainWindow", "USER"))


import picsIBM_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_SignUp()
    ui.setupUiSignUp(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
